const DISCRIMINATOR_BYTES = 8n;
const PUBKEY_BYTES = 32n;
const U64_BYTES = 8n;
const I64_BYTES = 8n;

const PLAN_MINT_OFFSET_LEN = DISCRIMINATOR_BYTES + PUBKEY_BYTES;
const PLAN_ID_OFFSET_LEN = PLAN_MINT_OFFSET_LEN + PUBKEY_BYTES;
const PLAN_AMOUNT_PER_PERIOD_OFFSET_LEN = PLAN_ID_OFFSET_LEN + U64_BYTES;
const PLAN_AMOUNT_EFFECTIVE_AT_OFFSET_LEN =
  PLAN_AMOUNT_PER_PERIOD_OFFSET_LEN + U64_BYTES;
const PLAN_PREVIOUS_AMOUNT_OFFSET_LEN =
  PLAN_AMOUNT_EFFECTIVE_AT_OFFSET_LEN + I64_BYTES;
const PLAN_PREVIOUS_EFFECTIVE_AT_OFFSET_LEN =
  PLAN_PREVIOUS_AMOUNT_OFFSET_LEN + U64_BYTES;
const PLAN_PERIOD_SECONDS_OFFSET_LEN =
  PLAN_PREVIOUS_EFFECTIVE_AT_OFFSET_LEN + I64_BYTES;
const PLAN_PRICE_MODE_OFFSET_LEN = PLAN_PERIOD_SECONDS_OFFSET_LEN + I64_BYTES;

export const PLAN_MERCHANT_OFFSET = DISCRIMINATOR_BYTES;
export const PLAN_IS_ACTIVE_OFFSET = PLAN_PRICE_MODE_OFFSET_LEN + 1n;

export const SUBSCRIPTION_SUBSCRIBER_OFFSET =
  DISCRIMINATOR_BYTES + PUBKEY_BYTES;
